# Generated by Django 5.1.6 on 2025-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('student_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='students/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
