# Generated by Django 5.1.4 on 2024-12-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('teacher_phone', models.CharField(max_length=15)),
                ('teacher_email', models.EmailField(max_length=100, unique=True)),
                ('work_experience', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='subjects.subject')),
            ],
        ),
    ]
